name: Build & test

on: [push]

jobs:
  php:
    name: PHP test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
    - name: Debug PHP and Composer
      run: |
        php --version
        php -m
        composer --version
    - name: Composer Install dependencies
      run: |
        composer install --prefer-dist --no-suggest
    - name: Composer Test
      run: |
        composer run test
